# Generated by Django 5.0.6 on 2024-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('cie_marks', models.IntegerField()),
                ('see_marks', models.IntegerField()),
                ('students', models.ManyToManyField(related_name='results', to='resultapp.student')),
            ],
        ),
    ]
