# Generated by Django 5.0.6 on 2024-07-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channelnum', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('channeltype', models.CharField(max_length=50)),
                ('number_of_viewers', models.IntegerField()),
            ],
        ),
    ]
