# Generated by Django 5.0.6 on 2024-07-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname1', models.CharField(max_length=50)),
                ('lname1', models.CharField(max_length=100)),
                ('aadhar1', models.IntegerField(max_length=12)),
                ('pincode1', models.IntegerField(max_length=6)),
            ],
        ),
    ]
