# Generated by Django 5.0.6 on 2024-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('aadhar', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='bank1',
        ),
    ]
