# Generated by Django 5.0.6 on 2024-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_name', models.CharField(max_length=255)),
                ('furniture_type', models.CharField(max_length=255)),
                ('features', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_used', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=255)),
                ('cphone', models.CharField(max_length=15)),
                ('cemail', models.EmailField(max_length=254)),
                ('purchase', models.ManyToManyField(related_name='purchased_by', to='furniture.furniture')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppler_name', models.CharField(max_length=255)),
                ('sphone', models.CharField(max_length=15)),
                ('semail', models.EmailField(max_length=254)),
                ('supply', models.ManyToManyField(related_name='supplied_by', to='furniture.furniture')),
            ],
        ),
    ]
